function cfg = build_hypothesis_config(hyp_dir, opts)
%BUILD_HYPOTHESIS_CONFIG Build a validate-ready cfg struct from decipher output.
%
%   cfg = BUILD_HYPOTHESIS_CONFIG(hyp_dir)
%   cfg = BUILD_HYPOTHESIS_CONFIG(hyp_dir, opts)
%
%   Reads the route_map.tsv, species_map.tsv, and S_matrix.tsv from a
%   hypothesis directory (generated by decipher_routes) and constructs a
%   cfg struct compatible with run_pipeline_generic.
%
%   If a config_hypothesis.m file exists in hyp_dir, it is loaded directly.
%   Otherwise, the config is built from the TSV files.
%
%   Inputs:
%     hyp_dir — path to a hypothesis directory containing:
%                 route_map.tsv, species_map.tsv, S_matrix.tsv
%                 [optional] config_hypothesis.m, rate_fn_template.m
%     opts    — struct with optional fields:
%       .organism            — organism name (default: 'Deciphered')
%       .condition           — condition key (default: 'COND1')
%       .experimental_data   — path to experimental data dir (optional)
%       .t_span              — [t0, tf] (default: [0, 72])
%       .t_eval              — time grid (default: 0:0.5:72)
%       .substrate_idx       — index of substrate species (default: 1)
%       .target_idx          — index of target species (default: auto)
%       .biomass_idx         — index of biomass species (default: last)
%       .rate_fn             — function handle for kinetics (default: auto)
%       .phenotype_type      — reference phenotype type (default: 'exponential_depletion')
%
%   Output:
%     cfg — struct compatible with run_pipeline_generic()
%
%   Example:
%     cfg = build_hypothesis_config('outputs/decipher_MO/hypotheses/hypothesis_1');
%     run_pipeline_generic(cfg);
%
%   See also: DECIPHER_ROUTES, RUN_PIPELINE_GENERIC, LOAD_GEM_TSV

    if nargin < 2, opts = struct(); end

    fprintf('\n=== BUILD HYPOTHESIS CONFIG ===\n');
    fprintf('  Source: %s\n', hyp_dir);

    % --- Check for pre-generated config ---
    config_file = fullfile(hyp_dir, 'config_hypothesis.m');
    if isfile(config_file)
        fprintf('  Found config_hypothesis.m — loading directly\n');
        old_path = addpath(hyp_dir);
        try
            % Find the config function
            [~, fn_name] = fileparts(config_file);
            cfg_fn = str2func(fn_name);
            cfg = cfg_fn();
            fprintf('  Config loaded from %s\n', config_file);
        catch ME
            warning('MRHP:build_config:ConfigError', ...
                    'Error loading config_hypothesis.m: %s\nBuilding from TSV instead.', ME.message);
            cfg = build_from_tsv(hyp_dir, opts);
        end
        path(old_path);
    else
        cfg = build_from_tsv(hyp_dir, opts);
    end

    % --- Overlay experimental data if provided ---
    if isfield(opts, 'experimental_data') && ~isempty(opts.experimental_data)
        cfg = overlay_experimental_data(cfg, opts.experimental_data, opts);
    end

    % --- Set output directory ---
    if isfield(opts, 'output_dir') && ~isempty(opts.output_dir)
        cfg.output_dir = opts.output_dir;
    elseif ~isfield(cfg, 'output_dir')
        cfg.output_dir = fullfile(hyp_dir, '..', '..', 'validate_output');
    end

    fprintf('=== CONFIG BUILT ===\n\n');
end

% =========================================================================
%  LOCAL FUNCTIONS
% =========================================================================

function cfg = build_from_tsv(hyp_dir, opts)
%BUILD_FROM_TSV Construct cfg from route_map, species_map, S_matrix TSVs.

    organism  = get_opt(opts, 'organism', 'Deciphered');
    cond_key  = get_opt(opts, 'condition', 'COND1');

    % --- Read TSV files ---
    rm_file = fullfile(hyp_dir, 'route_map.tsv');
    sm_file = fullfile(hyp_dir, 'species_map.tsv');
    sx_file = fullfile(hyp_dir, 'S_matrix.tsv');

    if ~isfile(rm_file) || ~isfile(sm_file) || ~isfile(sx_file)
        error('MRHP:build_config:MissingFiles', ...
              'Required files not found in %s. Need: route_map.tsv, species_map.tsv, S_matrix.tsv', hyp_dir);
    end

    route_map   = readtable(rm_file, 'FileType','text', 'Delimiter','\t', 'TextType','string');
    species_map = readtable(sm_file, 'FileType','text', 'Delimiter','\t', 'TextType','string');

    % Read S matrix
    sraw = readtable(sx_file, 'FileType','text', 'Delimiter','\t', 'TextType','string', ...
                     'VariableNamingRule','preserve');
    S = double(sraw{:, 2:end});
    n_sp  = size(S, 1);
    n_rxn = size(S, 2);

    fprintf('  Route map: %d reactions, %d species\n', n_rxn, n_sp);

    % --- Top-level config ---
    cfg.organism   = sprintf('%s (Deciphered)', organism);
    cfg.conditions = {cond_key};

    % Extract genes from route_map
    genes = {};
    gene_col = route_map{:, 5};  % gene column
    for i = 1:numel(gene_col)
        g = char(gene_col(i));
        if ~isempty(g) && ~strcmp(g, '')
            parts = regexp(g, '\s+(and|or)\s+', 'split');
            for pp = 1:numel(parts)
                gname = strtrim(parts{pp});
                gname = regexprep(gname, '[()]', '');
                if ~isempty(gname) && ~any(strcmp(genes, gname))
                    genes{end+1} = gname; %#ok<AGROW>
                end
            end
        end
    end
    if isempty(genes), genes = {'Gene1'}; end
    cfg.genes = genes;

    % --- Solver ---
    t_span = get_opt(opts, 't_span', [0, 72]);
    t_eval = get_opt(opts, 't_eval', (t_span(1):0.5:t_span(2))');
    cfg.solver.t_span    = t_span;
    cfg.solver.t_eval    = t_eval;
    cfg.solver.rtol      = 1e-8;
    cfg.solver.atol      = 1e-10;
    cfg.solver.max_step  = 0.5;
    cfg.solver.substrate_conversion = 1.0;

    % --- Sweep ---
    cfg.sweep.substrate_values = [1.0];
    cfg.sweep.target_values    = [1.0];
    cfg.ref_substrate = 1.0;
    cfg.ref_target    = 1.0;
    cfg.t_sample      = 24.0;

    % --- Expression ---
    cfg.expression.beta_m          = 8.32;
    cfg.expression.beta_p          = 0.924;
    cfg.expression.ktl             = 6.0;
    cfg.expression.stochastic_tau  = 0.01;
    cfg.expression.n_cells         = 20;
    cfg.expression.nm_to_mol       = 6022;

    % Transcription rates (default)
    for gi = 1:numel(genes)
        cfg.ktx_fits.(genes{gi}) = 0.1;
    end

    % --- Model ---
    sp_names = cellstr(species_map{:, 2});  % ode_name column
    m.species = sp_names(:)';
    m.S       = S;
    m.base_x0 = ones(n_sp, 1) * 0.1;
    m.base_x0(1) = 1.0;  % first species = substrate

    m.substrate_idx = get_opt(opts, 'substrate_idx', 1);
    target_idx_val  = get_opt(opts, 'target_idx', min(2, n_sp));
    m.target_idx    = target_idx_val;
    m.biomass_idx   = get_opt(opts, 'biomass_idx', n_sp);

    % Rate function
    if isfield(opts, 'rate_fn') && ~isempty(opts.rate_fn)
        m.rate_fn = opts.rate_fn;
    else
        % Check for rate_fn_template.m
        rate_files = dir(fullfile(hyp_dir, 'rate_fn_*.m'));
        if ~isempty(rate_files)
            old_path = addpath(hyp_dir);
            [~, fn_name] = fileparts(rate_files(1).name);
            m.rate_fn = str2func(fn_name);
            m.params  = struct();
            path(old_path);
            fprintf('  Using rate function: %s\n', fn_name);
        else
            % Generate inline Michaelis-Menten
            m.params.Vmax = ones(n_rxn, 1);
            m.params.Km   = 0.5 * ones(n_rxn, 1);
            m.rate_fn = @(x, params) default_mm_rate(x, S, params);
        end
    end

    cfg.models.(cond_key) = m;

    % --- Phi definition ---
    cfg.phi_definition.default = struct('type', 'depletion', 'target_idx', target_idx_val);

    % --- Phenotype reference ---
    ptype = get_opt(opts, 'phenotype_type', 'exponential_depletion');
    cfg.phenotype_ref.(cond_key) = struct('type', ptype, 'mu', 0.1);

    % --- Regulatory signals (default activation for all genes) ---
    for gi = 1:numel(genes)
        cfg.regulatory.(genes{gi}).default = struct(...
            'form', 'act', ...
            'signals', {{1}}, ...
            'K', [0.5], ...
            'n', [2], ...
            'basal', 0.01);
    end

    % --- Hypotheses ---
    cfg.hypotheses.(cond_key) = {struct('id', sprintf('HYP_%s_1', cond_key), ...
                                        'label', 'Deciphered route', ...
                                        'diagnostic_up', {genes}, ...
                                        'score_total', 0.5)};

    % --- Route maps ---
    cfg.route_maps.(cond_key) = struct(...
        'route_map',   fullfile(hyp_dir, 'route_map.tsv'), ...
        'species_map', fullfile(hyp_dir, 'species_map.tsv'), ...
        'S_matrix',    fullfile(hyp_dir, 'S_matrix.tsv'));

    % --- Visualization ---
    cfg.visualization.colors.(cond_key) = [0.2, 0.6, 0.8];
    cfg.visualization.labels.(cond_key) = cond_key;
end

function cfg = overlay_experimental_data(cfg, data_dir, opts)
%OVERLAY_EXPERIMENTAL_DATA Load experimental data into cfg if available.
    cond_key = cfg.conditions{1};

    % Check for RT-qPCR data
    rtqpcr_file = fullfile(data_dir, 'rtqpcr_absolute_processed.tsv');
    if isfile(rtqpcr_file)
        fprintf('  Loading RT-qPCR data from %s\n', rtqpcr_file);
        rtq = readtable(rtqpcr_file, 'FileType','text', 'Delimiter','\t', 'TextType','string');
        for gi = 1:numel(cfg.genes)
            gene = cfg.genes{gi};
            row = find(strcmpi(string(rtq{:,1}), gene), 1);
            if ~isempty(row)
                val = rtq{row, 2};
                if isnumeric(val)
                    cfg.experimental_data.(cond_key).(gene) = val;
                else
                    cfg.experimental_data.(cond_key).(gene) = str2double(val);
                end
            end
        end
    end

    % Check for kinetics data
    kinetics_file = fullfile(data_dir, 'decolorization_kinetics.csv');
    if isfile(kinetics_file)
        fprintf('  Loading kinetics data from %s\n', kinetics_file);
        % Store path reference; actual parsing depends on phenotype_ref type
        cfg.kinetics_data_file = kinetics_file;
    end

    % Check for expression parameter fits
    fits_file = fullfile(data_dir, 'expression_parameter_fits.tsv');
    if isfile(fits_file)
        fprintf('  Loading expression parameter fits from %s\n', fits_file);
        fits = readtable(fits_file, 'FileType','text', 'Delimiter','\t', 'TextType','string');
        for gi = 1:numel(cfg.genes)
            gene = cfg.genes{gi};
            row = find(strcmpi(string(fits{:,1}), gene), 1);
            if ~isempty(row) && width(fits) >= 2
                val = fits{row, 2};
                if isnumeric(val)
                    cfg.ktx_fits.(gene) = val;
                else
                    cfg.ktx_fits.(gene) = str2double(val);
                end
            end
        end
    end
end

function v = default_mm_rate(x, S, params)
%DEFAULT_MM_RATE Simple Michaelis-Menten rate for each reaction.
    n_rxn = size(S, 2);
    v = zeros(n_rxn, 1);
    for r = 1:n_rxn
        col = S(:, r);
        if issparse(col), col = full(col); end
        subs = find(col < 0);
        if ~isempty(subs)
            s_conc = max(x(subs(1)), 0);
            v(r) = params.Vmax(r) * s_conc / (params.Km(r) + s_conc);
        else
            v(r) = params.Vmax(r);
        end
    end
end

function v = get_opt(opts, field, default)
    if isfield(opts, field)
        v = opts.(field);
    else
        v = default;
    end
end
